### ISSUE TITLE
[bug] Request Signature Version

### ISSUE THREAD

**Issue by TheMoti** [QuentinPerez/go-radosgw#13]
Hi Quentin :)
There is a problem with signature function ```SignS3``` used from _awsauth_ lib, in which it always considers the first part of **four.parted.domain.names** as bucket name and uses it in the string it's gonna hash for creating the signature. I presume it doesn't do the same while decoding since it results in a ```SignatureDoesNotMatch``` error. removing that part from the signing process fixes the problem but _awsauth_ lib is deprecated and archived. This problem doesn't happen in the ```Sign4``` function though, but using ```SignS3``` is hard-coded in this lib. It would be nice if the api call gets the signature version as an input.

p.s. I just saw that go-ceph used your code for the radosgw which seems to use another signer. thank you.

**Comment by QuentinPerez** [comment]
Hi @TheMoti 👋 

Thank you for the report, but this project is no longer maintained as the code has been moved here https://github.com/ceph/go-ceph. Don't hesitate to open an issue, if needed.
