### ISSUE TITLE
Moving code to the Ceph organization?

### ISSUE THREAD

**Issue by leseb** [QuentinPerez/go-radosgw#8]
Salut @QuentinPerez,

Great work on that library!
I'm not sure if you are aware but the Ceph organization has a repository that centralizes [go-binding from various Ceph components](https://github.com/ceph/go-ceph) (currently RBD and CephFS). With the go-ceph team, we believe that go-ceph could benefit from this library and the other way around.
Having an official "home" under the Ceph organization banner is always good to get more traction, maintenance, and improvement.

It seems that there is no licensing issue, so let us know if you are on board with the idea.
Merci.

**Comment by QuentinPerez** [comment]
Salut @leseb

I have no time to maintain this project hence that would be with pleasure :), tell me how I can help to migrate the code !

Merci.

**Comment by leseb** [comment]
Merci for the quick response!
I can take care of that for you I suppose, just give me your sign-off so I can add you as a co-author to the contribution to go-ceph :).

**Comment by QuentinPerez** [comment]
`Sign-off: Quentin Perez <qperez42@gmail.com>` should be fine :)

**Comment by leseb** [comment]
https://github.com/ceph/go-ceph/pull/496
